#!/usr/tcl/bin/expect
set timeout 10
set username [lindex $argv 0]
set oldpassword [lindex $argv 1]
set hostname [lindex $argv 2]
set newpassword [lindex $argv 3]

spawn ssh $username@$hostname
expect {
"*yes/no)?" {
send "yes\r"; exp_continue
}
}
expect "password:"
send "$oldpassword\r"
expect "$"
send "sudo passwd centos\r"
expect "*password*:"
send "$oldpassword\r"
expect "New password:"
send "$newpassword\r"
expect "Retype*assword:"
send "$newpassword\r"
expect "*$"
send "exit\r"
